# Generated by Django 5.1.6 on 2025-02-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieStore", "0002_movie_description_movie_image_movie_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="movie_name",
            new_name="movie_id",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="id",
            new_name="movie_id",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="price",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="release_date",
        ),
        migrations.AddField(
            model_name="movie",
            name="dollar_price",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.CharField(
                choices=[
                    ("G", "G"),
                    ("PG", "PG"),
                    ("PG-13", "PG-13"),
                    ("R", "R"),
                    ("NC-17", "NC-17"),
                ],
                default="PG",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="release_year",
            field=models.IntegerField(default=2025, verbose_name="release date"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(),
        ),
    ]
