# Generated by Django 5.1.6 on 2025-02-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieStore", "0003_rename_movie_name_cart_movie_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="movie_id",
            new_name="movie_name",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="movie_id",
            new_name="id",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="dollar_price",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="release_year",
        ),
        migrations.AddField(
            model_name="movie",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="movie",
            name="release_date",
            field=models.DateField(default=2018, verbose_name="release date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(default="Not currently Available."),
        ),
    ]
