# Generated by Django 5.1.6 on 2025-02-14 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieStore", "0004_rename_movie_id_cart_movie_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
